### ISSUE TITLE
On Stream Review

### ISSUE THREAD

**Issue by braddotcoffee** [GiridharRNair/ProfStatsUTD#6]
## Hardcoded Values in Repo
* Starting from raw data, it would be nice to find a way to not have to commit the data itself but instead create some sort of process to retrieve the data - I'm not sure how you found this data so it might not be possible, but I'm sure you understand why it's suboptimal to have a ton of data just hardcoded in your repo
* A lot of places in the repo could use a combover looking to pull constants out
  * Urls that you make requests to
  * The default classes that you recommend in your "GetSuggestedCourses" DB function

## DB Schema
* I don't personally love how difficult it gets to work with your "courses" based around the schema of "APlus", "A", etc.
* It's nice in that you can just sum the grades by summing columns but again it feels super hardcoded to the way that your school does grades / reports their distribution
* In a prod environment you really wouldn't want to convey your "attribute" via N columns
* It would probably be better to turn this into 2 tables that are a 1->many relationship of instructor -> grade count

**Comment by GiridharRNair** [comment]
Thanks for taking the time to review my code!

Regarding the data source, you're absolutely right about the bad practice of hardcoding it into the repo. I plan to enhance this in the future by implementing a feature to dynamically retrieve data from the [UTD Grades](https://github.com/acmutd/utd-grades/tree/master/raw_data) repository's `raw_data` directory, addressing the concern you raised.

In the upcoming version 1.0.9, I have taken some constant out as per your discretion. Thanks for pointing that out!

I appreciate your suggestion about the DB schema and the potential complexity in handling grades. While I didn't fully grasp your proposed solution, I believe for the current project scope, the hardcoded SQL statements suffice. I'll keep your insights in mind for future iterations as the project evolves and features become more intricate.

Again, thank you so much for not only reviewing my code, but also for the generous $100 cloud credits giveaway!
